# Generated by Django 5.2.4 on 2025-07-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newcustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('customer_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=10)),
                ('mobile_number', models.CharField(max_length=10)),
                ('website', models.URLField(max_length=255)),
                ('tin_number', models.CharField(max_length=50)),
                ('opening_balance', models.PositiveBigIntegerField(max_length=1000)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('street_one', models.CharField(max_length=255)),
                ('street_two', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('postal_code', models.BigIntegerField(max_length=5)),
                ('country', models.CharField(max_length=255)),
                ('notes', models.TextField(max_length=1000)),
                ('attachments', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
