# Generated by Django 5.2.4 on 2025-07-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowaf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newcustomer',
            options={'ordering': ['customer_name']},
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
