# Generated by Django 5.2.4 on 2025-07-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowaf', '0002_alter_newcustomer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcustomer',
            name='actions',
            field=models.CharField(choices=[('create a sales receipt', 'create a sales receipt'), ('create a charge', 'create a charge'), ('create a time activity', 'create a time activity'), ('create a task', 'create a task'), ('make inactive', 'make inactive')], default='', max_length=255),
        ),
    ]
