# Generated by Django 5.2.4 on 2025-07-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowaf', '0003_newcustomer_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcustomer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
