# Generated by Django 5.2.4 on 2025-07-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowaf', '0004_alter_newcustomer_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcustomer',
            name='opening_balance',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='postal_code',
            field=models.BigIntegerField(),
        ),
    ]
