# Generated by Django 5.2.4 on 2025-07-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowaf', '0005_alter_newcustomer_opening_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('supplier_type', models.CharField(choices=[('Goods', 'Goods'), ('Services', 'Services'), ('Both', 'Both')], default='', max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='', max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_position', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=255)),
                ('website', models.URLField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=5)),
                ('country', models.CharField(max_length=255)),
                ('bank', models.CharField(max_length=255)),
                ('bank_accout', models.CharField(max_length=255)),
                ('bank_branch', models.CharField(max_length=255)),
                ('payment_terms', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
                ('payment_method', models.CharField(choices=[('Bank transafer', 'Bank transafer'), ('Cheque', 'Cheque'), ('Cash', 'Cash')], default='', max_length=255)),
                ('tin', models.CharField(max_length=255)),
                ('reg_number', models.CharField(max_length=255)),
                ('tax_rate', models.IntegerField()),
                ('attachments', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
