# Generated by Django 5.2.4 on 2025-07-16 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sowaf', '0007_alter_newsupplier_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsupplier',
            old_name='bank_accout',
            new_name='bank_account',
        ),
    ]
