# Generated by Django 5.2.4 on 2025-07-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowaf', '0008_rename_bank_accout_newsupplier_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsupplier',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
