# Generated by Django 5.2.4 on 2025-07-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sowaf', '0009_newsupplier_opening_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsupplier',
            old_name='opening_balance',
            new_name='open_balance',
        ),
    ]
