# Generated by Django 5.2.4 on 2025-07-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowaf', '0010_rename_opening_balance_newsupplier_open_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsupplier',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
