# Generated by Django 5.2.4 on 2025-07-18 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sowaf', '0012_newclient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newclient',
            old_name='contact_enail',
            new_name='contact_email',
        ),
    ]
