# Generated by Django 5.2.4 on 2025-07-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowaf', '0013_rename_contact_enail_newclient_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newclient',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
