# Generated by Django 5.2.4 on 2025-07-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowaf', '0015_alter_newclient_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newclient',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
