# Generated by Django 5.2.4 on 2025-07-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowaf', '0016_alter_newclient_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newemployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=255, null=True)),
                ('dob', models.DateField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('nin_number', models.CharField(blank=True, max_length=255, null=True)),
                ('tin_number', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=255, null=True)),
                ('residential_address', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_person', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('relationship', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Intern', 'Intern'), ('Volunteer', 'Volunteer')], default='', max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='', max_length=255, null=True)),
                ('hire_date', models.DateField(blank=True, max_length=255, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=255, null=True)),
                ('payment_frequency', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('Bank transafer', 'Bank transafer'), ('Cheque', 'Cheque'), ('Cash', 'Cash')], default='', max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('nssf_number', models.CharField(blank=True, max_length=255, null=True)),
                ('insurance_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('taxable_allowances', models.CharField(blank=True, max_length=255, null=True)),
                ('intaxable_allowances', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_attachments', models.FileField(upload_to='uploads/')),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
        migrations.AlterField(
            model_name='newclient',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=255, null=True),
        ),
    ]
