# Generated by Django 5.2.4 on 2025-07-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowaf', '0017_newemployee_alter_newclient_credit_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newemployee',
            name='additional_notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='newemployee',
            name='intaxable_allowances',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=255, null=True),
        ),
        migrations.AlterField(
            model_name='newemployee',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='newemployee',
            name='taxable_allowances',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=255, null=True),
        ),
    ]
