# Generated by Django 5.2.4 on 2025-07-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowaf', '0018_alter_newemployee_additional_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newemployee',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Terminated', 'Terminated')], default='', max_length=255, null=True),
        ),
    ]
