# Generated by Django 5.2.4 on 2025-07-20 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowaf', '0020_alter_newclient_tin_alter_newcustomer_actions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newemployee',
            options={},
        ),
        migrations.CreateModel(
            name='Newasset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_category', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_depreciation', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('custodian', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_status', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_price', models.CharField(blank=True, max_length=255, null=True)),
                ('warranty', models.CharField(blank=True, max_length=255, null=True)),
                ('funding_source', models.CharField(blank=True, max_length=255, null=True)),
                ('life_span', models.CharField(blank=True, max_length=255, null=True)),
                ('depreciation_method', models.CharField(blank=True, choices=[('Straight line', 'Straight line'), ('Reducing balance', 'Reducing balance')], max_length=255, null=True)),
                ('residual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remaining_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('asset_account', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capitalization_date', models.DateField()),
                ('cost_center', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_condition', models.CharField(blank=True, max_length=255, null=True)),
                ('maintenance_schedule', models.CharField(blank=True, max_length=255, null=True)),
                ('insurance_details', models.CharField(blank=True, max_length=255, null=True)),
                ('notes_details', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_attachments', models.FileField(upload_to='uploads/')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='sowaf.newsupplier')),
            ],
            options={
                'ordering': ['asset_name'],
            },
        ),
    ]
