# Generated by Django 5.2.4 on 2025-07-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowaf', '0021_alter_newemployee_options_newasset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newasset',
            old_name='residual_price',
            new_name='accumulated_depreciation',
        ),
        migrations.RenameField(
            model_name='newasset',
            old_name='asset_depreciation',
            new_name='asset_description',
        ),
        migrations.RenameField(
            model_name='newasset',
            old_name='notes_details',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='newasset',
            name='purchase_date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newasset',
            name='residual_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
