# Generated by Django 5.2.4 on 2025-07-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowaf', '0023_alter_newasset_capitalization_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newasset',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
