# Generated by Django 5.2.4 on 2025-07-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowaf', '0024_newasset_asset_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newasset',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
