# Generated by Django 5.2.4 on 2025-07-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowaf', '0025_alter_newasset_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newasset',
            name='asset_status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Disposed', 'Disposed'), ('Written-Off', 'Written-Off')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='newasset',
            name='depreciation_method',
            field=models.CharField(blank=True, choices=[('Straight line', 'Straight line'), ('Reducing balance', 'Reducing balance')], default='', max_length=255, null=True),
        ),
    ]
