# Generated by Django 5.2.4 on 2025-07-29 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sowaf", "0027_newinvoice_invoiceitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newasset",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplied_assets",
                to="sowaf.newsupplier",
            ),
        ),
        migrations.AlterField(
            model_name="newclient",
            name="contact",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
