# Generated by Django 5.2.4 on 2025-07-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sowaf", "0028_alter_newasset_supplier_alter_newclient_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newasset",
            name="capitalization_date",
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
