# Generated by Django 5.2.4 on 2025-07-29 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sowaf", "0030_alter_newasset_capitalization_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newasset",
            name="capitalization_date",
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="newasset",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplied_assets",
                to="sowaf.newsupplier",
            ),
        ),
    ]
