# Generated by Django 5.2.4 on 2025-07-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sowaf", "0031_alter_newasset_capitalization_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newasset",
            name="capitalization_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="newasset",
            name="supplier",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
