# Generated by Django 5.2.4 on 2025-07-31 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sowaf', '0033_alter_newasset_capitalization_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newinvoice',
            name='customer',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
        migrations.DeleteModel(
            name='Newinvoice',
        ),
    ]
