# Generated by Django 5.2.5 on 2025-08-25 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_banktransaction_loan_remove_transaction_posted_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Inventory", "Inventory"),
                            ("Non-Inventory", "Non-Inventory"),
                            ("Service", "Service"),
                            ("Bundle", "Bundle"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("sku", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("Good", "Good"), ("Service", "Service")],
                        max_length=20,
                    ),
                ),
                (
                    "class_field",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Class"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("sell_checkbox", models.BooleanField(default=False)),
                (
                    "sales_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("purchase_checkbox", models.BooleanField(default=False)),
                ("is_bundle", models.BooleanField(default=False)),
                ("display_bundle_contents", models.BooleanField(default=False)),
                (
                    "expense_account",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"type": "EXPENSE"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expense_products",
                        to="accounts.account",
                    ),
                ),
                (
                    "income_account",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"type": "INCOME"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="income_products",
                        to="accounts.account",
                    ),
                ),
                (
                    "inventory_account",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"type": "ASSET"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_products",
                        to="accounts.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BundleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "bundle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bundle_items",
                        to="inventory.product",
                    ),
                ),
            ],
        ),
    ]
