# Generated by Django 5.2.5 on 2025-08-25 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("sowaf", "0034_remove_newinvoice_customer_delete_invoiceitem_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="inventory_account",
        ),
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sowaf.newsupplier",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="expense_account",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="product",
            name="income_account",
            field=models.CharField(max_length=200),
        ),
    ]
