# Generated by Django 5.2.5 on 2025-08-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0002_remove_product_inventory_account_product_supplier_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_bundle",
        ),
        migrations.AlterField(
            model_name="product",
            name="expense_account",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="income_account",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
