# Generated by Django 5.2.5 on 2025-08-25 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_remove_product_is_bundle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bundleitem",
            name="product_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="used_in_bundle",
                to="inventory.product",
            ),
        ),
    ]
