# Generated by Django 5.2.5 on 2025-08-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_bundleitem_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_bundle",
            field=models.BooleanField(default=False),
        ),
    ]
