# Generated by Django 5.2.4 on 2025-07-31 18:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sowaf', '0034_remove_newinvoice_customer_delete_invoiceitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newinvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(editable=False, max_length=10, null=True, unique=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('invoice_due', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_address', models.CharField(blank=True, max_length=255, null=True)),
                ('terms', models.CharField(blank=True, max_length=255, null=True)),
                ('sales_rep', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('po_number', models.PositiveIntegerField(blank=True, null=True)),
                ('item_details', models.CharField(blank=True, max_length=255, null=True)),
                ('memo', models.CharField(blank=True, max_length=255, null=True)),
                ('customs_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='')),
                ('subtotal', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('tax', models.FloatField(default=0)),
                ('shipping', models.FloatField(default=0)),
                ('total_due', models.FloatField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sowaf.newcustomer')),
            ],
            options={
                'ordering': ['invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('qty', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billable', models.BooleanField(default=False)),
                ('tax', models.BooleanField(default=False)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.newinvoice')),
            ],
        ),
    ]
