# Generated by Django 5.2.5 on 2025-08-20 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20250820_1313"),
        ("sales", "0002_product_bundleitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="income_account",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"type": "INCOME"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="accounts.account",
            ),
        ),
    ]
