# Generated by Django 5.2.5 on 2025-08-25 07:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_banktransaction_loan_remove_transaction_posted_and_more"),
        ("inventory", "0001_initial"),
        ("sales", "0003_alter_product_income_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="income_account",
        ),
        migrations.RemoveField(
            model_name="invoiceitem",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="invoiceitem",
            name="rate",
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="income_account",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"type": "INCOME"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="line_total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="name_snapshot",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.product",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="qty",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("1.00"), max_digits=12
            ),
        ),
        migrations.DeleteModel(
            name="BundleItem",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
